"""pedido comercial: venta_pedido, cliente_facturacion

Revision ID: 5a6cbb11285f
Revises: fac2c9c5250e
Create Date: 2026-09-21 18:12:33.350187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6cbb11285f'
down_revision: Union[str, Sequence[str], None] = 'fac2c9c5250e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('tipo_cliente', sa.String(length=30), nullable=True))
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('ventas', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ventas', 'pedidos', ['pedido_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_column('ventas', 'pedido_id')
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('clientes', 'tipo_cliente')
    op.drop_column('clientes', 'ciudad')
    # ### end Alembic commands ###
