"""producto proveedor_id

Revision ID: fac2c9c5250e
Revises: c2acf78443b9
Create Date: 2026-09-21 17:54:33.615200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac2c9c5250e'
down_revision: Union[str, Sequence[str], None] = 'c2acf78443b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'proveedores', ['proveedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'proveedor_id')
    # ### end Alembic commands ###
