"""distribucion: venta_tipo pedido_hora

Revision ID: fca87d3259bf
Revises: 5a6cbb11285f
Create Date: 2026-09-21 18:26:33.256628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca87d3259bf'
down_revision: Union[str, Sequence[str], None] = '5a6cbb11285f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('hora_entrega', sa.String(length=50), nullable=True))
    op.add_column('ventas', sa.Column('tipo', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'tipo')
    op.drop_column('pedidos', 'hora_entrega')
    # ### end Alembic commands ###
